-- Which of the demo seed's accounts exist in this database. READ ONLY.
--
-- The demo seed creates 66 accounts that all share one published
-- password. If a database was ever seeded with it, they are a way in.
--
-- On the server, from the directory holding docker-compose.yml:
--
--   docker compose exec -T db sh -c 'psql -U "$POSTGRES_USER" -d "$POSTGRES_DB"' < demo-accounts-find.sql
--
-- Nothing is changed. Look at the list before running demo-accounts-suspend.sql:
-- an address you actually sign in with must go in that script's keep list.

\set ON_ERROR_STOP on
BEGIN READ ONLY;

WITH demo(email) AS (VALUES
  ('alex.rivera@globalbank.com'),
  ('asm@grcwisdom.com'),
  ('asset.owner@omniops.me'),
  ('billing@grcwisdom.com'),
  ('business.madinah@hayathospitals.com'),
  ('company.admin@omniops.me'),
  ('compliance.madinah@hayathospitals.com'),
  ('compliance@retailco.com'),
  ('consultant@grcconsulting.com'),
  ('eleanor.vance@globalbank.com'),
  ('engagement.manager@grcconsulting.com'),
  ('experience.madinah@hayathospitals.com'),
  ('finance.madinah@hayathospitals.com'),
  ('finance.manager@omniops.me'),
  ('finance@globalbank.com'),
  ('finance@grcconsulting.com'),
  ('finance@retailco.com'),
  ('franchisee.admin@retailco.com'),
  ('franchisor.admin@retailco.com'),
  ('grc.manager@omniops.me'),
  ('group.admin@alnoor.com'),
  ('group.compliance@alnoor.com'),
  ('group.finance@alnoor.com'),
  ('group.hr@alnoor.com'),
  ('group.risk@alnoor.com'),
  ('hr.madinah@hayathospitals.com'),
  ('hr.manager@omniops.me'),
  ('hr@globalbank.com'),
  ('hr@grcconsulting.com'),
  ('hr@grcwisdom.com'),
  ('hr@retailco.com'),
  ('internal.audit@omniops.me'),
  ('marcus.thorne@auditco.com'),
  ('marketplace@grcwisdom.com'),
  ('network.admin@givc.com.sa'),
  ('network.support@retailco.com'),
  ('owner@grcwisdom.com'),
  ('partner.owner@grcconsulting.com'),
  ('post.sales@grcconsulting.com'),
  ('postsales@alnoor.com'),
  ('postsales@globalbank.com'),
  ('postsales@grcwisdom.com'),
  ('postsales@omniops.me'),
  ('postsales@retailco.com'),
  ('presales@alnoor.com'),
  ('presales@globalbank.com'),
  ('presales@grcconsulting.com'),
  ('presales@grcwisdom.com'),
  ('presales@omniops.me'),
  ('presales@retailco.com'),
  ('risk.madinah@hayathospitals.com'),
  ('risk.manager@omniops.me'),
  ('risk@globalbank.com'),
  ('risk@grcconsulting.com'),
  ('risk@grcwisdom.com'),
  ('risk@retailco.com'),
  ('sarah.jenkins@globalbank.com'),
  ('security.manager@omniops.me'),
  ('security@grcwisdom.com'),
  ('servicedesk@grcwisdom.com'),
  ('success@grcwisdom.com'),
  ('support.coordinator@omniops.me'),
  ('support.madinah@hayathospitals.com'),
  ('support@alnoor.com'),
  ('support@globalbank.com'),
  ('top.management@omniops.me')
)
SELECT u.email, u.name, u.role, u.status, t.name AS organisation, t.type AS organisation_type, u."createdAt"::date AS created,
       CASE WHEN t.type IN ('SAAS', 'SAAS_UNIT') THEN 'PLATFORM ACCOUNT: keep it if you sign in with it' ELSE '' END AS note
FROM "User" u
JOIN "Tenant" t ON t.id = u."tenantId"
WHERE lower(u.email) IN (SELECT email FROM demo)
ORDER BY t.type IN ('SAAS', 'SAAS_UNIT') DESC, t.name, u.email;

WITH demo(email) AS (VALUES
  ('alex.rivera@globalbank.com'),
  ('asm@grcwisdom.com'),
  ('asset.owner@omniops.me'),
  ('billing@grcwisdom.com'),
  ('business.madinah@hayathospitals.com'),
  ('company.admin@omniops.me'),
  ('compliance.madinah@hayathospitals.com'),
  ('compliance@retailco.com'),
  ('consultant@grcconsulting.com'),
  ('eleanor.vance@globalbank.com'),
  ('engagement.manager@grcconsulting.com'),
  ('experience.madinah@hayathospitals.com'),
  ('finance.madinah@hayathospitals.com'),
  ('finance.manager@omniops.me'),
  ('finance@globalbank.com'),
  ('finance@grcconsulting.com'),
  ('finance@retailco.com'),
  ('franchisee.admin@retailco.com'),
  ('franchisor.admin@retailco.com'),
  ('grc.manager@omniops.me'),
  ('group.admin@alnoor.com'),
  ('group.compliance@alnoor.com'),
  ('group.finance@alnoor.com'),
  ('group.hr@alnoor.com'),
  ('group.risk@alnoor.com'),
  ('hr.madinah@hayathospitals.com'),
  ('hr.manager@omniops.me'),
  ('hr@globalbank.com'),
  ('hr@grcconsulting.com'),
  ('hr@grcwisdom.com'),
  ('hr@retailco.com'),
  ('internal.audit@omniops.me'),
  ('marcus.thorne@auditco.com'),
  ('marketplace@grcwisdom.com'),
  ('network.admin@givc.com.sa'),
  ('network.support@retailco.com'),
  ('owner@grcwisdom.com'),
  ('partner.owner@grcconsulting.com'),
  ('post.sales@grcconsulting.com'),
  ('postsales@alnoor.com'),
  ('postsales@globalbank.com'),
  ('postsales@grcwisdom.com'),
  ('postsales@omniops.me'),
  ('postsales@retailco.com'),
  ('presales@alnoor.com'),
  ('presales@globalbank.com'),
  ('presales@grcconsulting.com'),
  ('presales@grcwisdom.com'),
  ('presales@omniops.me'),
  ('presales@retailco.com'),
  ('risk.madinah@hayathospitals.com'),
  ('risk.manager@omniops.me'),
  ('risk@globalbank.com'),
  ('risk@grcconsulting.com'),
  ('risk@grcwisdom.com'),
  ('risk@retailco.com'),
  ('sarah.jenkins@globalbank.com'),
  ('security.manager@omniops.me'),
  ('security@grcwisdom.com'),
  ('servicedesk@grcwisdom.com'),
  ('success@grcwisdom.com'),
  ('support.coordinator@omniops.me'),
  ('support.madinah@hayathospitals.com'),
  ('support@alnoor.com'),
  ('support@globalbank.com'),
  ('top.management@omniops.me')
)
SELECT count(*) FILTER (WHERE lower(u.email) IN (SELECT email FROM demo)) AS demo_accounts_present,
       count(*) FILTER (WHERE lower(u.email) IN (SELECT email FROM demo) AND u.status = 'Active') AS of_which_active,
       count(*) FILTER (WHERE lower(u.email) NOT IN (SELECT email FROM demo)) AS other_accounts
FROM "User" u;

ROLLBACK;
