/**
 * The format-independent shape of a report.
 *
 * Content is decided once and rendered three ways. Without this the five
 * reports would each need an Excel, a PDF and a Word implementation — fifteen
 * places for the same figure to drift.
 */

export type Provenance = {
  reportName: string;
  tenantName: string;
  generatedBy: string;
  scopeKind: string;
  /** Present when the report covers one engagement. */
  subjectStatus?: string;
  subjectRef?: string;
};

export type Column = { header: string; key: string; width?: number };

export type ReportSection =
  | { kind: 'fields'; title: string; fields: { label: string; value: string }[] }
  | { kind: 'table'; title: string; columns: Column[]; rows: Record<string, any>[] };

/**
 * How a report is dressed, as opposed to what it says.
 *
 * One field rather than a widening Provenance, because these are two different
 * kinds of fact: provenance is what the report asserts about its own making,
 * chrome is how the page looks. Slice 7's five reports each build their own
 * sections and provenance; none of them should have to know what a brand colour
 * is, and none of them will need a renderer change to get one.
 *
 * Note what is NOT here: which sections to include, a date range, a format.
 * Those are arguments to the report BUILDER in the controller. A renderer that
 * could decide to omit a section is a renderer each report has to be tested
 * against separately.
 */
export type ReportChrome = {
  /** The organisation the report is issued in the name of. */
  displayName: string;
  /** #RRGGBB. Chrome only — never a warning. See tenantBranding.UNBRANDABLE. */
  brandColour: string;
  /** The brand where it is legible on paper, ink where it is not. */
  textColour: string;
  /** Public | Internal | Confidential | Restricted, stamped on every page. */
  marking: string;
  footerText: string | null;
  /**
   * PNG or JPEG bytes, already read from the store by the controller.
   *
   * A Buffer rather than a path or a base64 string because pdfkit's doc.image()
   * accepts exactly that — a string argument is treated as a filesystem path,
   * so passing base64 fails with ENOENT rather than anything that reads like a
   * type error.
   */
  logo: Buffer | null;
  /**
   * Stable reference minted once per export, printed on every page.
   *
   * Two copies of a report that differ are the thing nobody can untangle six
   * months later; a reference on the page is how someone says which one they
   * are holding.
   */
  documentRef: string;
  /**
   * Stamped once by the caller, not read per renderer.
   *
   * Otherwise a long render puts a different minute on the cover than in the
   * footer, and a reader who notices has to wonder what else disagrees.
   */
  generatedAt: Date;
};

export type ReportDocument = {
  provenance: Provenance;
  sections: ReportSection[];
  /** Optional so existing callers keep working; defaulted by the renderers. */
  chrome?: ReportChrome;
};

export type ReportFormat = 'xlsx' | 'pdf' | 'docx';
export const FORMATS: ReportFormat[] = ['xlsx', 'pdf', 'docx'];

export const MIME: Record<ReportFormat, string> = {
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  pdf: 'application/pdf',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
};

/**
 * A report taken before an engagement closes is a draft, and must say so on
 * its face — otherwise a working copy circulates looking like an issued
 * opinion. Returns null when there is nothing to warn about.
 */
export function draftNotice(p: Provenance): string | null {
  if (!p.subjectStatus || p.subjectStatus === 'Closed') return null;
  return `DRAFT — this engagement is ${p.subjectStatus}. Figures are provisional and the conclusion is not final.`;
}

export function provenanceRows(
  p: Provenance,
  at: Date = new Date(),
  ref?: string,
): { label: string; value: string }[] {
  const rows = [{ label: 'Organisation', value: p.tenantName }];
  if (p.subjectRef) rows.push({ label: 'Engagement', value: p.subjectRef });
  if (p.subjectStatus) rows.push({ label: 'Engagement status at export', value: p.subjectStatus });
  rows.push(
    { label: 'Generated by', value: p.generatedBy },
    { label: 'Generated at', value: stampOf(at) },
    { label: 'Visibility', value: p.scopeKind },
  );
  if (ref) rows.push({ label: 'Document reference', value: ref });
  return rows;
}

/** One rendering of the timestamp, so the cover and the footer cannot disagree. */
export const stampOf = (at: Date = new Date()): string =>
  `${at.toISOString().replace('T', ' ').slice(0, 16)} UTC`;

/**
 * The default dressing, for a caller that supplies none.
 *
 * Every field is populated, so a renderer never branches on absence — the one
 * place a missing logo is handled is here.
 */
export function defaultChrome(p: Provenance): ReportChrome {
  return {
    displayName: p.tenantName,
    brandColour: '#0F7A5A',
    textColour: '#0F7A5A',
    marking: 'Confidential',
    footerText: null,
    logo: null,
    documentRef: '',
    generatedAt: new Date(),
  };
}

/** Safe, dated filename — Windows rejects several of these characters. */
export function fileNameFor(reportName: string, format: ReportFormat, ref?: string): string {
  const stamp = new Date().toISOString().slice(0, 10);
  const base = [reportName, ref].filter(Boolean).join('_');
  return `${base.replace(/[^A-Za-z0-9_-]+/g, '_')}_${stamp}.${format}`;
}

export const cellText = (v: any): string =>
  v === null || v === undefined || v === '' ? '' : String(v);
