/**
 * The format-independent shape of a report.
 *
 * Content is decided once and rendered three ways. Without this the five
 * reports would each need an Excel, a PDF and a Word implementation — fifteen
 * places for the same figure to drift.
 */

export type Provenance = {
  reportName: string;
  tenantName: string;
  generatedBy: string;
  scopeKind: string;
  /** Present when the report covers one engagement. */
  subjectStatus?: string;
  subjectRef?: string;
};

export type Column = { header: string; key: string; width?: number };

export type ReportSection =
  | { kind: 'fields'; title: string; fields: { label: string; value: string }[] }
  | { kind: 'table'; title: string; columns: Column[]; rows: Record<string, any>[] };

export type ReportDocument = {
  provenance: Provenance;
  sections: ReportSection[];
};

export type ReportFormat = 'xlsx' | 'pdf' | 'docx';
export const FORMATS: ReportFormat[] = ['xlsx', 'pdf', 'docx'];

export const MIME: Record<ReportFormat, string> = {
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  pdf: 'application/pdf',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
};

/**
 * A report taken before an engagement closes is a draft, and must say so on
 * its face — otherwise a working copy circulates looking like an issued
 * opinion. Returns null when there is nothing to warn about.
 */
export function draftNotice(p: Provenance): string | null {
  if (!p.subjectStatus || p.subjectStatus === 'Closed') return null;
  return `DRAFT — this engagement is ${p.subjectStatus}. Figures are provisional and the conclusion is not final.`;
}

export function provenanceRows(p: Provenance): { label: string; value: string }[] {
  const rows = [{ label: 'Organisation', value: p.tenantName }];
  if (p.subjectRef) rows.push({ label: 'Engagement', value: p.subjectRef });
  if (p.subjectStatus) rows.push({ label: 'Engagement status at export', value: p.subjectStatus });
  rows.push(
    { label: 'Generated by', value: p.generatedBy },
    { label: 'Generated at', value: `${new Date().toISOString().replace('T', ' ').slice(0, 16)} UTC` },
    { label: 'Visibility', value: p.scopeKind },
  );
  return rows;
}

/** Safe, dated filename — Windows rejects several of these characters. */
export function fileNameFor(reportName: string, format: ReportFormat, ref?: string): string {
  const stamp = new Date().toISOString().slice(0, 10);
  const base = [reportName, ref].filter(Boolean).join('_');
  return `${base.replace(/[^A-Za-z0-9_-]+/g, '_')}_${stamp}.${format}`;
}

export const cellText = (v: any): string =>
  v === null || v === undefined || v === '' ? '' : String(v);
